development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: factorypeople_development
  pool: 5
  hostname: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: factorypeople_test
  pool: 5
  username: root
  password:
  hostname: localhost