development:
  port: 9312
  morphology: stem_en
  min_infix_len: 2
  enable_star: true

test:
  port: 9313
  morphology: stem_en
  min_infix_len: 2
  enable_star: true

production:
  port: 9312
  morphology: stem_en
  min_infix_len: 2
  enable_star: true
